// Generated by CoffeeScript 1.3.3
(function() {
  var consolex, fs, spinner, spinnerLoop;

  fs = require('fs');

  consolex = require('./console-xtra');

  exports.getAccount = function(accounts, accountType) {
    var randomAcc, tempAccArray, tempRandomAccount;
    tempRandomAccount = {
      username: '',
      password: '',
      site: ''
    };
    tempAccArray = accounts.filter(function(el) {
      return el.accountType === accountType;
    });
    if (tempAccArray.length > 0) {
      randomAcc = Math.floor(Math.random() * tempAccArray.length);
      tempRandomAccount.username = tempAccArray[randomAcc].loginID;
      tempRandomAccount.password = tempAccArray[randomAcc].password;
      tempRandomAccount.site = tempAccArray[randomAcc].siteName;
    } else {
      tempRandomAccount.username = 'no accounts';
    }
    return tempRandomAccount;
  };

  spinner = function(x) {
    var temp3, tempSpinner, tempStr, y;
    tempStr = '';
    tempSpinner = x.split(/\{([^}]+)\}/);
    y = 0;
    while (y < tempSpinner.length) {
      temp3 = tempSpinner[y].split("|");
      tempStr += temp3[Math.floor(temp3.length * Math.random())];
      ++y;
    }
    return tempStr;
  };

  spinnerLoop = function(x) {
    var tempArray, y;
    tempArray = [];
    y = 0;
    while (y < x.length) {
      tempArray[y] = spinner(x[y]);
      ++y;
    }
    return tempArray;
  };

  exports.getArticle = function(articles, microBlog, noHTML) {
    var a, floatPos, newArticle, randomFloat, randomImage, randomKeyword, randomLink, randomPos, temp, temp1, temp2, temp3, tempIndex, tempLink, tempRandom;
    a = Math.floor(articles.length * Math.random());
    newArticle = {
      title: '',
      body: '',
      keywords: [],
      links: [],
      images: []
    };
    if (a >= articles.length) {
      a = articles.length - 1;
    }
    consolex.log('blue', 'Spinning title for article # ' + a + '...');
    newArticle.title = spinner(articles[a].title);
    consolex.log('blue', 'Spinning keywords for article # ' + a + '...');
    newArticle.keywords = spinnerLoop(articles[a].keywords);
    consolex.log('blue', 'Spinning links for article # ' + a + '...');
    newArticle.links = spinnerLoop(articles[a].links);
    consolex.log('blue', 'Spinning images for article # ' + a + '...');
    newArticle.images = spinnerLoop(articles[a].images);
    consolex.log('blue', 'Spinning body of article # ' + a + '...');
    if (microBlog) {
      temp = articles[a].description;
    } else {
      temp = articles[a].body;
    }
    newArticle.body = spinner(temp);
    if (noHTML) {
      newArticle.body = newArticle.body.replace('<br>', '\n');
    }
    consolex.log('blue', 'Inserting random links in article # ' + a + '...');
    if (!noHTML) {
      tempIndex = 0;
      while (tempIndex < newArticle.keywords.length) {
        if (newArticle.keywords[tempIndex].trim().length === 0) {
          newArticle.keywords.splice(tempIndex, 1);
        }
        ++tempIndex;
      }
      if (newArticle.keywords.length === 0) {
        newArticle.keywords[0] = 'here';
      }
      if ((newArticle.body.indexOf("#links#")) === -1) {
        newArticle.body += ' #links#';
      }
      while ((newArticle.body.indexOf("#links#")) !== -1) {
        tempRandom = Math.floor(Math.random() * newArticle.links.length);
        randomLink = newArticle.links[tempRandom];
        tempRandom = Math.floor(Math.random() * newArticle.keywords.length);
        randomKeyword = newArticle.keywords[tempRandom];
        tempLink = ' <a href="' + randomLink.toString().trim() + '">' + randomKeyword.toString().trim() + '</a> ';
        newArticle.body = newArticle.body.replace('#links#', tempLink);
      }
    } else {
      newArticle.body = newArticle.body.replace('#links#', ' ');
      temp = Math.floor(Math.random() * newArticle.links.length);
      randomLink = newArticle.links[temp];
      newArticle.body += ' ' + randomLink;
    }
    if (!noHTML) {
      consolex.log('blue', 'Inserting random image in article # ' + a + '...');
      temp = newArticle.body.length;
      floatPos = ['style="float:right"', 'style="float:left"'];
      randomFloat = Math.round(Math.random());
      randomPos = Math.ceil(Math.random() * temp);
      randomImage = Math.floor(Math.random() * newArticle.images.length);
      while (newArticle.body.charAt(randomPos - 1) !== ' ') {
        randomPos = Math.ceil(Math.random() * temp);
      }
      temp1 = newArticle.body.slice(0, randomPos);
      temp2 = '<img src="' + newArticle.images[randomImage] + '" ' + floatPos[randomFloat] + '>';
      temp3 = newArticle.body.slice(randomPos, temp);
      newArticle.body = temp1 + temp2 + temp3;
    }
    consolex.log('magenta', 'Created article: ' + newArticle.title);
    return newArticle;
  };

  exports.getProfile = function(profiles, noHTML) {
    var a, newProfile, randomKeyword, randomLink, temp, tempIndex, tempLink, tempRandom;
    a = Math.floor(profiles.length * Math.random());
    if (a >= profiles.length) {
      a = profiles.length - 1;
    }
    newProfile = {
      username: '',
      password: '',
      sitename: '',
      email: profiles[a].email,
      profile: '',
      keywords: [],
      links: []
    };
    consolex.log('blue', 'Spinning username for profile # ' + a + '...');
    newProfile.username = spinner(profiles[a].username);
    consolex.log('blue', 'Spinning password for profile # ' + a + '...');
    newProfile.password = spinner(profiles[a].password);
    consolex.log('blue', 'Spinning sitename for profile # ' + a + '...');
    newProfile.sitename = spinner(profiles[a].sitename);
    consolex.log('blue', 'Spinning keywords for profile # ' + a + '...');
    newProfile.keywords = spinnerLoop(profiles[a].keywords);
    consolex.log('blue', 'Spinning links for profile # ' + a + '...');
    newProfile.links = spinnerLoop(profiles[a].links);
    consolex.log('blue', 'Spinning profile # ' + a + '...');
    newProfile.profile = spinner(profiles[a].profile);
    if (noHTML) {
      newProfile.profile = newProfile.profile.replace('<br>', '\n');
    }
    consolex.log('blue', 'Inserting random links in profile # ' + a + '...');
    if (!noHTML) {
      tempIndex = 0;
      while (tempIndex < newProfile.keywords.length) {
        if (newProfile.keywords[tempIndex].trim().length === 0) {
          newProfile.keywords.splice(tempIndex, 1);
        }
        ++tempIndex;
      }
      if (newProfile.keywords.length === 0) {
        newProfile.keywords[0] = 'here';
      }
      if ((newProfile.profile.indexOf("#links#")) === -1) {
        newProfile.profile += ' #links#';
      }
      while ((newProfile.profile.indexOf("#links#")) !== -1) {
        tempRandom = Math.floor(Math.random() * newProfile.links.length);
        randomLink = newProfile.links[tempRandom];
        tempRandom = Math.floor(Math.random() * newProfile.keywords.length);
        randomKeyword = newProfile.keywords[tempRandom];
        tempLink = ' <a href="' + randomLink.toString().trim() + '">' + randomKeyword.toString().trim() + '</a> ';
        newProfile.profile = newProfile.profile.replace('#links#', tempLink);
      }
    } else {
      newProfile.profile = newProfile.profile.replace('#links#', ' ');
      temp = Math.floor(Math.random() * newProfile.links.length);
      randomLink = newProfile.links[temp];
      newProfile.profile += ' ' + randomLink;
    }
    consolex.log('magenta', 'Created profile: ' + newProfile.username);
    return newProfile;
  };

}).call(this);
